// Copies each UI component's source into a TS module so pages can show the real code.
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const uiDir = join(process.cwd(), "src", "components", "ui");
const outDir = join(process.cwd(), "src", "generated");
const sources = {};

for (const file of readdirSync(uiDir).filter((f) => f.endsWith(".tsx")).sort()) {
  sources[file.replace(/\.tsx$/, "")] = readFileSync(join(uiDir, file), "utf8").replace(/\r\n/g, "\n");
}

mkdirSync(outDir, { recursive: true });
writeFileSync(
  join(outDir, "sources.ts"),
  `// Generated by scripts/generate-sources.mjs. Do not edit.\nexport const sources: Record<string, string> = ${JSON.stringify(sources, null, 2)};\n`,
);
console.log(`Generated sources for ${Object.keys(sources).length} components.`);
